rvm: 1.9.2
bundler_args: "--without development production"
before_script:
  - "sh -c 'cp config/database.example.yml config/database.yml'"
  - "sh -c 'bundle exec rake db:migrate'"
  - "sh -c 'bundle exec rake db:test:prepare'"
